import Joi from '@hapi/joi';

export default {
  productFormData: Joi.object().keys({
    productCategoryId: Joi.number().required(),
    productItemName: Joi.string().required().max(100),
    productItemSKU: Joi.string().required().max(50),
    productItemDescription: Joi.string().optional(),
    file: Joi.string().optional().uri(),
    productIsActive: Joi.number().optional(),
    productStoreId: Joi.number().optional(),
    productItemExpiry: Joi.date().optional(),
    productIsTaxable: Joi.number().optional(),
    productTaxPercentage: Joi.number().optional(),
    productItemBarCode: Joi.string().required().max(20),
    productPurchasedPrice: Joi.number().optional(),
    productQuantity: Joi.number().required(),
    productItemBrand: Joi.string().optional().max(100),
    productUnitPrice: Joi.number().required(),
    productComparativePrice: Joi.number().optional(),
    productImage: Joi.string().optional().allow(''),
  }),
  updateProductData: Joi.object().keys({
    productId: Joi.number().required(),
    productCategoryId: Joi.number().required(),
    productItemName: Joi.string().required().max(100),
    productItemDescription: Joi.string().optional(),
    productStoreId: Joi.number().optional(),
    file: Joi.string().optional().uri(),
    productIsActive: Joi.number().optional(),
    productItemExpiry: Joi.date().optional(),
    productIsTaxable: Joi.number().optional(),
    productTaxPercentage: Joi.number().optional(),
    productPurchasedPrice: Joi.number().optional(),
    productQuantity: Joi.number().required(),
    productItemBrand: Joi.string().optional().max(100),
    productUnitPrice: Joi.number().required(),
    productComparativePrice: Joi.number().optional(),
    productItemSKU: Joi.string().required().max(50),
    productItemBarCode: Joi.string().required().max(20),
    productItemImage: Joi.string().optional(),
  }),
  file: Joi.object().keys({
    file: Joi.string().optional().uri(),
  }),
  productList: Joi.object().keys({
    subCategoryId: Joi.number().optional(),
    productCategoryId: Joi.number().optional(),
    storeId: Joi.number().optional(),
    allProducts: Joi.number().optional(),
    search: Joi.object().optional(),
  }),
};
